server:
  port: 8081

spring:
  application:
    name: mock-gateway
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  level:
    com.gateway: INFO
